# Generated by Django 4.1 on 2022-11-19 04:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(default=payments.models.gen_id, max_length=50),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("volume", models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name="TelegramGroup",
            fields=[
                ("group_id", models.IntegerField(primary_key=True, serialize=False)),
                ("group_title", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (-1, "Not Started"),
                            (0, "Unconfirmed"),
                            (1, "Partially Confirmed"),
                            (2, "Confirmed"),
                        ],
                        default=-1,
                    ),
                ),
                ("order_id", models.CharField(max_length=250)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("btcvalue", models.FloatField(blank=True, null=True)),
                ("received", models.FloatField(blank=True, null=True)),
                ("txid", models.CharField(blank=True, max_length=250, null=True)),
                ("rbf", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateField(default=datetime.date.today)),
                ("rate", models.FloatField(blank=True, default=0)),
                ("settled", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=5000)),
                ("media", models.CharField(max_length=200)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(default=payments.models.gen_id, max_length=100),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("settled", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="payments.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupPermitted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.ManyToManyField(to="payments.telegramgroup")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
