# Generated by Django 4.1 on 2022-11-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="media_type",
            field=models.IntegerField(default=0),
        ),
    ]
