# Generated by Django 4.1 on 2023-01-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_post_media_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Button",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="telegramgroup",
            name="group_id",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
