# Generated by Django 4.1.5 on 2023-01-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_button_alter_telegramgroup_group_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Button",
        ),
        migrations.AddField(
            model_name="post",
            name="buttons",
            field=models.CharField(default=str, max_length=1000),
        ),
        migrations.AddField(
            model_name="post",
            name="duration",
            field=models.CharField(default=str, max_length=20),
        ),
        migrations.AddField(
            model_name="post",
            name="groups",
            field=models.CharField(default=str, max_length=1000),
        ),
    ]
