# Generated by Django 4.1 on 2022-11-19 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        default="1000",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="user id (telegram)",
                    ),
                ),
                ("date_added", models.DateField(default=datetime.date.today)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("balance", models.FloatField(default=float)),
                ("slots", models.IntegerField(default=0)),
                ("banned", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
